development:
  adapter: postgresql
  encoding: unicode
  database: tizi_development
  pool: 5
  username: vlad
  password: nikita

test:
  adapter: postgresql
  encoding: unicode
  database: tizi_test
  pool: 5
  username: vlad
  password: nikita

production:
  adapter: postgresql
  encoding: unicode
  database:
  username:
  password:
